(display "Enter the first number: ")
(define Num1 (read))
(display "Enter the second number: ")
(define Num2 (read))
(display (string-append "Choose a operation:\n1) Addition\n2) Subtraction\n3) Division\n4) Multiplication\n"))
(define calcType (read))
(cond ((= calcType 1) (display (format "Result:  ~a" (+ Num1 Num2))))
      ((= calcType 2) (display (format "Result:  ~a" (- Num1 Num2))))
      ((= calcType 3) (display (format "Result:  ~a" (/ Num1 Num2))))
      ((= calcType 4) (display (format "Result:  ~a" (* Num1 Num2))))
      (else (display "Not a valid operation")))